# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.31.17"
  config.vm.synced_folder "D:/VirtualBox/Vagrant", "/home/vagrant/share"
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y python3
     apt-get install -y python3-pip
     apt-get install python3-dev libpq-dev
     python3 -m pip install psycopg2
     python3 -m pip install django
     cp D:/VirtualBox/Vagrant/script.sh /home/vagrant/share/script.sh
   SHELL

end
